CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    gender INT NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    active INT DEFAULT 1,
    dob DATE NOT NULL,
    profile VARCHAR(255) NOT NULL,
    role INT DEFAULT 0, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
);


CREATE TABLE categories(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
);


CREATE TABLE blogs(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 user_id BIGINT,
 category_id BIGINT,
 title VARCHAR(255) NOT NULL,
 description MEDIUMTEXT NOT NULL,
 blog_img VARCHAR(255) NOT NULL,
 is_publish BOOLEAN DEFAULT 0,
 view_count INT DEFAULT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
 FOREIGN KEY (user_id) REFERENCES users(id),
 FOREIGN KEY (category_id) REFERENCES categories(id)
);
